### ISSUE TITLE
Can the build step be replaced by using the prebuilt qgis image?

### ISSUE THREAD

**Issue by mnboos** [boundlessgeo/qgis-testing-environment-docker#6]
Is it possible to use the qgis image available on dockerhub, instead of building qgis on my own?

Maybe the problem is, I don't know how to correctly start qgis on the console (i.e. without gui), in order to run python tests.

It always hangs with the message:

> Warning: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'

**Comment by Gustry** [comment]
I might be wrong, but you don't need to use Boundless image anymore for testing a QGIS plugin. This work has been integrated into QGIS core since QGIS 3.4.

Check the readme: https://github.com/qgis/QGIS/blob/master/.docker/README.md

And the InaSAFE plugin is using QGIS images for instance: https://github.com/inasafe/inasafe/blob/develop/.travis.yml#L9

**Comment by mnboos** [comment]
Oh awesome, I didn't see that. Thanks a lot!
